---
default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - pre-push
  - prepare-commit-msg
  - commit-msg
  - post-commit
  - post-checkout
  - post-merge
  - post-rewrite

fail_fast: false

repos:

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
      - id: clang-format
